In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
books = []

categories = [
    "Programming",
    "AI",
    "Data Science",
    "Database",
    "Analytics",
    "Mathematics"
]

for i in range(1, 101):

    books.append([
        f"B{i:03}",
        f"Book_{i}",
        f"Author_{i}",
        random.choice(categories),
        random.randint(300, 1500),
        random.randint(10, 100)
    ])

books_df = pd.DataFrame(
    books,
    columns=[
        "Book_ID",
        "Title",
        "Author",
        "Category",
        "Price",
        "Stock"
    ]
)

books_df.to_csv(
    "../data/books.csv",
    index=False
)

books_df.head()

  Book_ID   Title    Author   Category  Price  Stock
0    B001  Book_1  Author_1         AI    977     93
1    B002  Book_2  Author_2         AI    941     49
2    B003  Book_3  Author_3         AI   1061     94
3    B004  Book_4  Author_4  Analytics    787     59
4    B005  Book_5  Author_5  Analytics   1289     81

In [3]:
cities = [
    "Hyderabad",
    "Delhi",
    "Mumbai",
    "Pune",
    "Bangalore",
    "Chennai"
]

customers = []

for i in range(1, 201):

    customers.append([
        f"C{i:03}",
        f"Customer_{i}",
        random.randint(18, 60),
        random.choice(["M", "F"]),
        random.choice(cities)
    ])

customers_df = pd.DataFrame(
    customers,
    columns=[
        "Customer_ID",
        "Name",
        "Age",
        "Gender",
        "City"
    ]
)

customers_df.to_csv(
    "../data/customers.csv",
    index=False
)

customers_df.head()

  Customer_ID        Name  Age Gender       City
0        C001  Customer_1   59      M       Pune
1        C002  Customer_2   52      M     Mumbai
2        C003  Customer_3   36      F       Pune
3        C004  Customer_4   54      F  Hyderabad
4        C005  Customer_5   26      F    Chennai

In [4]:
sales = []

start_date = datetime(2024, 1, 1)

for i in range(1, 5001):

    sales.append([
        f"S{i:05}",
        f"B{random.randint(1,100):03}",
        f"C{random.randint(1,200):03}",
        random.randint(1,5),
        (
            start_date +
            timedelta(
                days=random.randint(
                    0,
                    730
                )
            )
        ).strftime("%Y-%m-%d")
    ])

sales_df = pd.DataFrame(
    sales,
    columns=[
        "Sale_ID",
        "Book_ID",
        "Customer_ID",
        "Quantity",
        "Date"
    ]
)

sales_df.to_csv(
    "../data/sales.csv",
    index=False
)

sales_df.head()

  Sale_ID Book_ID Customer_ID  Quantity        Date
0  S00001    B033        C128         3  2025-12-22
1  S00002    B035        C048         4  2025-06-14
2  S00003    B011        C086         2  2024-09-27
3  S00004    B042        C085         5  2025-01-31
4  S00005    B053        C081         1  2025-09-22

In [5]:
print("Books:", len(books_df))
print("Customers:", len(customers_df))
print("Sales:", len(sales_df))

Books: 100
Customers: 200
Sales: 5000