In [1]:
import pandas as pd

books = pd.read_csv("../data/books.csv")

books.head()

  Book_ID   Title    Author   Category  Price  Stock
0    B001  Book_1  Author_1         AI    977     93
1    B002  Book_2  Author_2         AI    941     49
2    B003  Book_3  Author_3         AI   1061     94
3    B004  Book_4  Author_4  Analytics    787     59
4    B005  Book_5  Author_5  Analytics   1289     81

In [2]:
books["Features"] = (
    books["Title"] + " " +
    books["Author"] + " " +
    books["Category"]
)

books.head()

,Book_ID,Title,Author,Category,Price,Stock,Features
0,B001,Book_1,Author_1,AI,977,93,Book_1 Author_1 AI
1,B002,Book_2,Author_2,AI,941,49,Book_2 Author_2 AI
2,B003,Book_3,Author_3,AI,1061,94,Book_3 Author_3 AI
3,B004,Book_4,Author_4,Analytics,787,59,Book_4 Author_4 Analytics
4,B005,Book_5,Author_5,Analytics,1289,81,Book_5 Author_5 Analytics

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
vectorizer = TfidfVectorizer()

feature_matrix = vectorizer.fit_transform(
    books["Features"]
)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
similarity_matrix = cosine_similarity(
    feature_matrix
)

In [7]:
def recommend_books(book_title):

    index = books[
        books["Title"] == book_title
    ].index[0]

    similarity_scores = list(
        enumerate(
            similarity_matrix[index]
        )
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    print("\nRecommended Books:\n")

    for book in similarity_scores[1:6]:

        idx = book[0]

        print(
            books.iloc[idx]["Title"]
        )

In [8]:
recommend_books("Book_10")

Recommended Books:

Book_11
Book_17
Book_28
Book_35
Book_52

In [9]:
import pickle

In [10]:
pickle.dump(
    similarity_matrix,
    open(
        "../models/recommendation_model.pkl",
        "wb"
    )
)